-- Create chat_messages table for the chatting section
CREATE TABLE IF NOT EXISTS chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  message text NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL
);

-- Enable RLS policies for chat_messages table
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access on chat_messages" ON chat_messages FOR ALL USING (true) WITH CHECK (true);
